services:
  spring-service:
    build: .
    container_name: mock-api
    ports:
      - "8910:8080"

  db:
    image: postgres:18.3
    container_name: ecommerce-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres